language: node_js
cache: yarn
node_js:
  - node
  - lts/*
script: npm run ci
jobs:
  include:
    - stage: semantic-release
      if: branch = master
      node_js: node
      script:
        - npm run build
        - npm run release
